version: "3.8"
services:
  web:
    build:
      context: ../src
    restart: always
    environment:
      DB_HOST: db
    depends_on:
      - db
      - worker
  worker:
    build:
      context: ../src
    restart: always
    environment:
      DB_HOST: db
    depends_on:
      - db
    entrypoint: ["python", "-m", "crawler"]
    extra_hosts:
      - "localhost:host-gateway"
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=web_crawler
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always


volumes:
  postgres_data: